# Makefile.consumer: template for scaffold-ci generated Makefiles.
# Placeholders substituted by scaffold-ci at generation time.
#
# AUTO-GENERATED by ../CI/scripts/scaffold-ci [2026-07-04T18:27:59Z]
# Source: ci-profile.yaml | tier=strict | languages=rust
# Re-generate: make -C ../CI scaffold-ci CONSUMER=. --force
#
# Language-specific targets (lint, type-check, test, check-push) are
# intentional vacuous passes. Fill them in per your project's stack.

SHELL := /bin/bash
.DEFAULT_GOAL := help

REPO_ROOT := $(shell git rev-parse --show-toplevel || pwd)
CI_DIR := $(abspath $(REPO_ROOT)/../CI)

-include $(CI_DIR)/lib/makefile_contract.mk

# =============================================================================
# Help
# =============================================================================
.PHONY: help
help: ## Show this help
	@grep -hE '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-20s\033[0m %s\n", $$1, $$2}'

# =============================================================================
# Setup
# =============================================================================
.PHONY: preflight init install install-ci install-deps install-hooks sync
preflight: ## Verify environment
	@test -d "$(CI_DIR)" || { echo "ERROR: CI directory not found at $(CI_DIR)" >&2; exit 1; }
	@test -f "$(CI_DIR)/scripts/generate-hooks" || { echo "ERROR: generate-hooks missing" >&2; exit 1; }
	@echo "Preflight OK"

init: ## Install system-level dependencies
	@echo "TODO: implement per-project system dependencies."
	@:

install: install-deps install-hooks ## Full install: deps + hooks
	@:

install-ci: install-deps ## CI install: deps only, no hooks
	@:

install-deps: ## Install project dependencies
	@echo "TODO: implement per-project dependency install."
	@:

install-hooks: ## (Re)generate native git hooks
	bash $(CI_DIR)/scripts/generate-hooks

sync: install-deps install-hooks ## Sync deps + reinstall hooks
	@:

# =============================================================================
# Quality Gates
# =============================================================================
.PHONY: check lint type-check test check-push clean clean-precommit

check: lint type-check test ## Run all quality gates
	@echo "TODO: wire lint+type-check+test implementations."

lint: ## Lint
	@:

type-check: ## Type-check
	@:

test: ## Test
	@:

check-push: ## Pre-push quality gate
	@:

# =============================================================================
# Cleanup
# =============================================================================
clean: ## Remove build artifacts
	@echo "TODO: implement per-project clean."
	@:

clean-precommit: ## Remove pre-commit framework traces
	bash $(CI_DIR)/scripts/cleanup-precommit
