#!/usr/bin/env bash
# Build the gateway-treemap panel: concatenate the sources into a single AMD
# module and copy the static plugin files. No bundler, no dependencies.
#
# Usage: build.sh [OUT_DIR]   (default: <plugin dir>/dist)
#
# Run from the repository root or from the plugin directory. The source
# directory can also be pinned with GATEWAY_TREEMAP_DIR.
set -euo pipefail

locate_here() {
    if [ -n "${GATEWAY_TREEMAP_DIR:-}" ] && [ -f "$GATEWAY_TREEMAP_DIR/src/panel.js" ]; then
        printf '%s\n' "$GATEWAY_TREEMAP_DIR"
        return
    fi
    if [ -f "$PWD/res/grafana-plugins/gateway-treemap/src/panel.js" ]; then
        printf '%s\n' "$PWD/res/grafana-plugins/gateway-treemap"
        return
    fi
    if [ -f "$PWD/src/panel.js" ]; then
        printf '%s\n' "$PWD"
        return
    fi
    echo "build.sh: cannot locate the gateway-treemap source directory" >&2
    exit 1
}

here="$(locate_here)"
out="${1:-$here/dist}"

mkdir -p "$out/img"

{
    echo "/* gateway-treemap: generated by build.sh - edit src/ instead. */"
    cat "$here/src/constraints.js"
    echo
    cat "$here/src/face.js"
    echo
    cat "$here/src/panel.js"
} > "$out/module.js"

cp "$here/plugin.json" "$out/plugin.json"
cp "$here/README.md" "$out/README.md"
cp "$here/img/logo.svg" "$out/img/logo.svg"

echo "[gateway-treemap] built $out/module.js ($(wc -c < "$out/module.js") bytes)"