resolver:
  - 10.89.0.1
  - 10.89.1.1

deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  admin:
    admin_key:
      - name: admin
        key: ${{ADMIN_KEY}}
        role: admin
    allow_admin:
      - 0.0.0.0/0
    enable_admin_ui: true
  etcd:
    host:
      - "http://etcd:2379"
    prefix: "/apisix"
    timeout: 30

plugins:
  - key-resolver
  - key-meta
  - ai-rate-limiting
  - proxy-buffering
  - proxy-rewrite
  - http-logger
  - prometheus
  - request-id
  - redact
  - sse-usage
  - limit-count
plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9100
    metrics:
      http_status:
        extra_labels:
          - key_hash: $http_x_key_hash
      http_latency:
        extra_labels:
          - key_hash: $http_x_key_hash
      bandwidth:
        extra_labels:
          - key_hash: $http_x_key_hash
      llm_latency:
        extra_labels:
          - key_hash: $http_x_key_hash
      llm_prompt_tokens:
        extra_labels:
          - key_hash: $http_x_key_hash
      llm_completion_tokens:
        extra_labels:
          - key_hash: $http_x_key_hash
      llm_active_connections:
        extra_labels:
          - key_hash: $http_x_key_hash

nginx_config:
  envs:
    - OPENCODE_API_KEY
    - OPENBAO_TOKEN
  http:
    custom_lua_shared_dict:
      redact_state: 1m
      key_cache: 5m
      gateway-cache: 2m
      quota_counters: 5m
    proxy_buffering: "on"
