FROM apache/apisix:3.17.0-debian

COPY plugins/custom/key-resolver.lua /usr/local/apisix/apisix/plugins/key-resolver.lua
COPY plugins/custom/key-meta.lua /usr/local/apisix/apisix/plugins/key-meta.lua
COPY plugins/custom/oauth-auth.lua /usr/local/apisix/apisix/plugins/oauth-auth.lua
COPY plugins/custom/oauth_broker.lua /usr/local/apisix/apisix/plugins/oauth_broker.lua
COPY plugins/custom/oauth_session.lua /usr/local/apisix/apisix/plugins/oauth_session.lua
COPY plugins/custom/oauth_jwt.lua /usr/local/apisix/apisix/plugins/oauth_jwt.lua
COPY plugins/custom/oauth_device.lua /usr/local/apisix/apisix/plugins/oauth_device.lua
COPY plugins/custom/oauth_store.lua /usr/local/apisix/apisix/plugins/oauth_store.lua
COPY plugins/custom/provider-sync.lua /usr/local/apisix/apisix/plugins/provider-sync.lua
COPY plugins/custom/provider_sync_catalog.lua /usr/local/apisix/apisix/plugins/provider_sync_catalog.lua
COPY plugins/custom/provider_sync_aliases.lua /usr/local/apisix/apisix/plugins/provider_sync_aliases.lua
COPY plugins/custom/provider_sync_contract.lua /usr/local/apisix/apisix/plugins/provider_sync_contract.lua
COPY plugins/custom/sse-usage.lua /usr/local/apisix/apisix/plugins/sse-usage.lua
COPY plugins/custom/sse_usage_lib.lua /usr/local/apisix/apisix/plugins/sse_usage_lib.lua
COPY plugins/custom/cost_calc.lua /usr/local/apisix/apisix/plugins/cost_calc.lua
COPY plugins/custom/model_registry.lua /usr/local/apisix/apisix/plugins/model_registry.lua
COPY plugins/custom/provider_sync_pricing.lua /usr/local/apisix/apisix/plugins/provider_sync_pricing.lua
COPY plugins/custom/provider_pricing.lua /usr/local/apisix/apisix/plugins/provider_pricing.lua
COPY plugins/custom/redact.lua /usr/local/apisix/apisix/plugins/redact.lua
COPY plugins/custom/redact_lib.lua /usr/local/apisix/apisix/plugins/redact_lib.lua
COPY plugins/custom/redact_walk.lua /usr/local/apisix/apisix/plugins/redact_walk.lua
COPY conf/config.yaml /usr/local/apisix/conf/config.yaml
COPY conf/redact-patterns.json /etc/apisix/redact-patterns.json
COPY conf/providers /usr/local/apisix/conf/providers

EXPOSE 9080 9443 9100
